# Site wide configuration

title: instantofu
locale: en_US
description: Be the Hero of Your Own Story.
description-de: Sollte. Hätte. Könnte. Würde. Machen!
description-vn: Đẹp Trai, Giầu Có, Chịu Khó và Tự Tin.
logo: site-logo.png
search: true
url: http://instantofu.eu

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "theme-setup", "no-upload"]


# Site owner
owner:
  name: instantofu
  avatar: hn-ava-2.jpg
  email: you@email.com
  disqus-shortname: instantofu
  twitter: instantofu
  facebook: instantofu
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: instantofu
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: instantofu
    analytics: UA-62262269-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
